defaults:
    - task: cls
    - model: ssg
    - task_model: ${defaults.0.task}-${defaults.1.model}
    - _self_

hydra:
  run:
    dir: outputs

gpus:
    - 0

optimizer: ???

task_model: ???

model: ???

distrib_backend: dp
